title: LibrariesWest
tagline: Thoughts from the systems team
description: ''
url: https://librarieswest.github.io
baseurl: ''
permalink: pretty
author:
  name: Dave Rowe
  url: 
  email: dxrowe@somerset.gov.uk
version: 1.0.0
github:
  repo: 'https://github.com/LibrariesWest'